version: '3.8'

services:
  app-blue:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod,s3Bucket
      TZ: Asia/Seoul
    networks:
      - app-network

  app-green:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod,s3Bucket
      TZ: Asia/Seoul
    networks:
      - app-network

networks:
  app-network:
    name: blue-green-network