spring:
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000
      password:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8080/login/oauth2/code/google
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000
      password:

app:
  front-url: http://localhost:3000

jwt:
  access-expired: 300 # 5분
  refresh-expired: 7200 # 2시간