spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: https://api.camping-on.site/login/oauth2/code/google

app:
  front-url: https://camping-on.site

jwt:
  access-expired: 900 # 15분
  refresh-expired: 86400 # 1일