server:
  port: 3000

aws:
  s3:
    bucket:
      stack.auto: false
      credentials:
        accessKey: ${S3_ACCESS_KEY}
        secretAccessKey: ${S3_SECRET_KEY}
      region: ap-northeast-2
      name: campingon

spring:
  config:
    activate:
      on-profile: s3Bucket