spring:
  datasource:
    url: ${MYSQL_URL}  # Prevent H2 from closing when JVM shuts down
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    database: mysql
    show-sql: true  # Log SQL statements
    hibernate:
      ddl-auto: update  # mysql 테이블 생성하고 싶으면 create 변경
    database-platform: org.hibernate.dialect.MySQLDialect  # Explicit dialect (optional for H2)
    properties:
      hibernate:
        format_sql: true  # Pretty-print SQL in logs
        auto_quote_keyword: true
  sql:
    init:
      mode: always  # Always run SQL scripts during initialization
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
  profiles:
    active: dev, s3Bucket #logback-spring springProfile 설정, AWS S3 Bucket 설정

public-data:
  go-camping: ${GO_CAMPING_SERVICE_KEY}

jwt:
  secret-key: ${JWT_SECRET_KEY}

app:
  pagination:
    reservation:
      size: 10