spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8080/login/oauth2/code/google

jwt:
  access-expired: 300 # 5분
  refresh-expired: 7200 # 2시간